"""Closed vocabularies shared by the whole runtime."""
from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:  # pragma: no cover - trivial
        return str(self.value)


class RequestMode(StrEnum):
    AUTHORING_DRAFT = "AUTHORING_DRAFT"
    FINALIZATION = "FINALIZATION"
    REVIEW_ONLY = "REVIEW_ONLY"
    META = "META"


class Scope(StrEnum):
    INDEPENDENT = "INDEPENDENT"
    DEPENDENT_SET = "DEPENDENT_SET"
    DEPENDENT_SINGLE = "DEPENDENT_SINGLE"


class Status(StrEnum):
    PASS = "PASS"
    PASS_RANGE = "PASS-RANGE"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"
    UNVERIFIED = "UNVERIFIED"


class ExecStatus(StrEnum):
    RUN = "RUN"
    GATE_NOT_RUN = "GATE_NOT_RUN"
    BLIND_COMPLETE = "BLIND_COMPLETE"
    UNVERIFIED = "UNVERIFIED"


class GateValue(StrEnum):
    PASS = "PASS"
    PASS_RANGE = "PASS-RANGE"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"
    UNVERIFIED = "UNVERIFIED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    LOCKED = "LOCKED"
    UNLOCKED = "UNLOCKED"
    RETURN_TO_DRAFTER = "RETURN_TO_DRAFTER"
    RETURN_TO_ARCHITECT = "RETURN_TO_ARCHITECT"
    RETURN_TO_DEPENDENT_ARCHITECT = "RETURN_TO_DEPENDENT_ARCHITECT"
    RETURN_TO_STYLE_ADJUSTER = "RETURN_TO_STYLE_ADJUSTER"


class NextStep(StrEnum):
    PROCEED = "PROCEED"
    RETURN_TO_DRAFTER = "RETURN_TO_DRAFTER"
    RETURN_TO_ARCHITECT = "RETURN_TO_ARCHITECT"
    RETURN_TO_DEPENDENT_ARCHITECT = "RETURN_TO_DEPENDENT_ARCHITECT"
    RETURN_TO_STYLE_ADJUSTER = "RETURN_TO_STYLE_ADJUSTER"
    USER_DECISION = "USER_DECISION"
    STOP = "STOP"


class FinalizedStatus(StrEnum):
    FINALIZED_FOR_SUCCESS = "FINALIZED_FOR_SUCCESS"
    NOT_FINALIZED = "NOT_FINALIZED"


class StyleChangeMode(StrEnum):
    INITIAL_FROM_DRAFTER = "INITIAL_FROM_DRAFTER"
    DRAFTER_REVISION = "DRAFTER_REVISION"
    STYLE_ONLY_REVISION = "STYLE_ONLY_REVISION"


class CandidateClass(StrEnum):
    TECHNICAL_SOLUTION_CANDIDATE = "TECHNICAL_SOLUTION_CANDIDATE"
    FALLBACK_ONLY = "FALLBACK_ONLY"
    DRAWING_ONLY = "DRAWING_ONLY"
    UNVERIFIED = "UNVERIFIED"
    RETURN_TO_ARCHITECT = "RETURN_TO_ARCHITECT"


class Sketchability(StrEnum):
    YES = "YES"
    PARTIAL = "PARTIAL"
    NO = "NO"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class InventionPrimary(StrEnum):
    PHYSICAL = "PHYSICAL"
    PROCESS = "PROCESS"
    DATA_CONTROL = "DATA_CONTROL"
    COMPOSITION = "COMPOSITION"


# Closed list of reason codes used by role files. Unknown values are mapped to OTHER.
REASON_CODES = {
    "SPEC_NOT_PROVIDED",
    "PRIOR_ART_NOT_PROVIDED",
    "INPUT_MISSING",
    "INPUT_MISSING_OR_REVISION_MISMATCH",
    "INPUT_REVISION_MISMATCH",
    "DEPENDENT_REVISION_MISMATCH",
    "UPSTREAM_GATE_NOT_PASS",
    "DEPENDENT_UPSTREAM_GATE_NOT_PASS",
    "UPSTREAM_STYLE_GATE_NOT_PASS",
    "UPSTREAM_OA_GATE_NOT_PASS",
    "BLIND_INPUT_CONTAMINATED",
    "BLIND_NOT_COMPLETE",
    "REFERENCE_MISSING",
    "LOCK_MISSING_OR_STALE",
    "ROOT_LOCK_MISSING_OR_STALE",
    "NO_TECHNICAL_SOLUTION_CANDIDATE",
    "AUXILIARY_SOURCE_MISSING",
    "REQUEST_MODE_MISSING_OR_INVALID",
    "CONFIG_VERSION_MISMATCH",
    "OTHER",
}

GATE_NAMES = [
    "DESIGN_GATE",
    "DRAFTER_GATE",
    "TERM_EXPRESSION_GATE",
    "CLAIM_STYLE_GATE",
    "NON_PATENT_TECHNICAL_READER_GATE",
    "GEOMETRIC_OBJECT_GATE",
    "OA_DRAFT_GATE",
    "OA_FINAL_GATE",
    "DEPENDENT_DESIGN_GATE",
    "DEPENDENT_OA_DRAFT_GATE",
    "DEPENDENT_OA_FINAL_GATE",
    "INVENTIVE_STEP",
    "PRE_STYLE_NON_PATENT_TECHNICAL_READER_CHECK",
    "PRE_STYLE_GEOMETRIC_OBJECT_CHECK",
]

RETURN_STEPS = {
    NextStep.RETURN_TO_DRAFTER,
    NextStep.RETURN_TO_ARCHITECT,
    NextStep.RETURN_TO_DEPENDENT_ARCHITECT,
    NextStep.RETURN_TO_STYLE_ADJUSTER,
}


def normalize_reason(code: str | None) -> str | None:
    if code is None or code == "":
        return None
    code = code.strip().upper().replace(" ", "_")
    return code if code in REASON_CODES else "OTHER"
